### ISSUE TITLE
Publish package on PyPI

### ISSUE THREAD

**Issue by JWCook** [lsaffre/sphinxfeed#2]
I would like to help get this published on PyPI! Here are a few things we would need:
* Package name: `sphinxfeed` is already taken, so we'll need a new name. Maybe `sphinx-feedgen`? Any other ideas?
* LICENSE file
* Possibly some additional package metadata

And here are a few items I'd recommend, but are optional:
* CI config: Automate building and publishing the package, triggered by git tags.
    * I could set this up with GitHub Actions, unless there's another CI tool you'd prefer.
* PyPI authentication: Using a [PyPI trusted publisher](https://docs.pypi.org/trusted-publishers) is a newer recommended way to publish packages, and doesn't require storing an API token.
    * I could set this up on PyPI and then add you as an owner, or you could set this up under your own account if you prefer.

Some other items to consider later, not specific to packaging:
* Publish docs to readthedocs.io: A single page with README contents would be fine.
* Automate tests with CI
    * Since test output varies based on dependency versions (Sphinx, docutils, and maybe others), this would require updating the tests to ignore minor variations that don't matter (formatting/whitespace, `lastBuildDate`, etc.). Another option would be using a packaging tool that produces lockfiles.
    * Test both rst and markdown input
    * Test both RSS and Atom output

**Comment by lsaffre** [comment]
Package name: sphinxfeed-lsaffre rather than sphinx-feedgen because the *module* name remains sphinxfeed and because it's a fork of the original sphinxfeed. But shouldn't we actually file an issue on https://github.com/pypa/pypi-support because AFAICS the original sphinxfeed project is abandoned. There are rules about claiming a package name: https://peps.python.org/pep-0541/

Regarding license my favourite is GPLv3, but I'm open to your suggestions.

**Comment by JWCook** [comment]
I think we can call this done. I will make a separate issue for test updates.

Thanks for working with me on this!
